eng_url_list = [
    "the-hindu-analysis-pdf",
    "business-line-newspaper",
    "the-economic-times-epaper",
    "hindustan-times-newspaper-download",
    "the-times-of-india-newspaper-pdf-download",
    "the-telegraph-newspaper",
    "business-standard-newspaper-download",
    "first-india-epaper",
    "telangana-today-newspaper",
    "mumbai-mirror-epaper-pdf",
    "the-financial-express-epaper-pdf",
    "hans-india-epaper",
    "mint-newspaper",
    "the-statesman-epaper-pdf",
    "tribune-newspaper",
    "the-asian-age-epaper-pdf",
    "deccan-chronicle-newspaper",
    "greater-kashmir-epaper-pdf",
    "the-pioneer-newspaper",
    "free-press-journal-epaper",
    "oheraldo-epaper-pdf",
    "nagaland-post-epaper-pdf",
    "state-times-epaper-pdf",
    "assam-tribune-epaper-pdf",
    "arunachal-times-epaper-pdf",
    "millennium-post-epaper",
    "deccan-herald-epaper-pdf-download",
    "lokmat-times-epaper-pdf",
    "kashmir-times-epaper-pdf"
]

eng_name_list = [
    "The Hindu Analysis",
    "Business Line",
    "The Economic Times",
    "Hindustan Times",
    "The Times of India",
    "The Telegraph",
    "Business Standard",
    "First India",
    "Telangana Today",
    "Mumbai Mirror",
    "The Financial Express",
    "Hans India",
    "Mint",
    "The Statesman",
    "The Tribune",
    "The Asian Age",
    "Deccan Chronicle",
    "Greater Kashmir",
    "The Pioneer",
    "Free Press Journal",
    "Oheraldo",
    "Nagaland Post",
    "State Times",
    "Assam Tribune",
    "Arunachal Times",
    "Millennium Post",
    "Deccan Herald",
    "Lokmat Times",
    "Kashmir Times",
    None
]